"""Initial migration

Revision ID: 8b9200e066ee
Revises: 
Create Date: 2025-06-14 19:15:56.647084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9200e066ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('used_osep', sa.Boolean(), nullable=False),
    sa.Column('used_bars', sa.Boolean(), nullable=False),
    sa.Column('bars_login', sa.String(), nullable=True),
    sa.Column('bars_password', sa.String(), nullable=True),
    sa.Column('osep_login', sa.String(), nullable=True),
    sa.Column('osep_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
