"""Добавлены таблицы global_config и user_config

Revision ID: a1b2c3d4e5f6
Revises: 999f1f840a68
Create Date: 2025-07-04 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '999f1f840a68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'global_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('poll_interval', sa.Integer(), server_default='60', nullable=False),
        sa.Column('max_poll_interval', sa.Integer(), server_default='600', nullable=False),
        sa.Column('timeout', sa.Integer(), server_default='30', nullable=False),
        sa.Column('stagger_delay', sa.Float(), server_default='2.0', nullable=False),
        sa.Column('stagger_jitter', sa.Float(), server_default='3.0', nullable=False),
        sa.Column('auto_scale_enabled', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('user_poll_mode', sa.String(length=20), server_default='global', nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'user_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('poll_interval', sa.Integer(), nullable=True),
        sa.Column('auto_scale_enabled', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )

    # Вставляем дефолтную запись в global_config
    op.execute(
        "INSERT INTO global_config (poll_interval, max_poll_interval, timeout, "
        "stagger_delay, stagger_jitter, auto_scale_enabled, user_poll_mode) "
        "VALUES (60, 600, 30, 2.0, 3.0, true, 'global')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_config')
    op.drop_table('global_config')
    # ### end Alembic commands ###
